version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: your-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: iluminacao
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
